### ISSUE TITLE
ashlar - set OMP_NUM_THREADS=1

### ISSUE THREAD

**Issue by jmuhlich** [sorgerlab/o2-deployment#1]
Set `OMP_NUM_THREADS=1` in the Ashlar module to avoid fftw's automatic threading, which is a hindrance rather than a help in this application.

**Comment by dpwrussell** [comment]
This was resolved in https://github.com/sorgerlab/o2-deployment/commit/05040a7f224ed62c032f439dc0db417f3ebbcd25
